# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import primerl_pb2 as primerl__pb2

GRPC_GENERATED_VERSION = '1.68.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in primerl_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PrimeRLStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartEpisode = channel.unary_unary(
                '/primerl.PrimeRL/StartEpisode',
                request_serializer=primerl__pb2.StartReq.SerializeToString,
                response_deserializer=primerl__pb2.StartResp.FromString,
                _registered_method=True)
        self.Step = channel.stream_stream(
                '/primerl.PrimeRL/Step',
                request_serializer=primerl__pb2.StepReq.SerializeToString,
                response_deserializer=primerl__pb2.StepResp.FromString,
                _registered_method=True)
        self.EndEpisode = channel.unary_unary(
                '/primerl.PrimeRL/EndEpisode',
                request_serializer=primerl__pb2.EndReq.SerializeToString,
                response_deserializer=primerl__pb2.EndResp.FromString,
                _registered_method=True)


class PrimeRLServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StartEpisode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Step(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EndEpisode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PrimeRLServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartEpisode': grpc.unary_unary_rpc_method_handler(
                    servicer.StartEpisode,
                    request_deserializer=primerl__pb2.StartReq.FromString,
                    response_serializer=primerl__pb2.StartResp.SerializeToString,
            ),
            'Step': grpc.stream_stream_rpc_method_handler(
                    servicer.Step,
                    request_deserializer=primerl__pb2.StepReq.FromString,
                    response_serializer=primerl__pb2.StepResp.SerializeToString,
            ),
            'EndEpisode': grpc.unary_unary_rpc_method_handler(
                    servicer.EndEpisode,
                    request_deserializer=primerl__pb2.EndReq.FromString,
                    response_serializer=primerl__pb2.EndResp.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'primerl.PrimeRL', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('primerl.PrimeRL', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PrimeRL(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StartEpisode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/primerl.PrimeRL/StartEpisode',
            primerl__pb2.StartReq.SerializeToString,
            primerl__pb2.StartResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Step(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/primerl.PrimeRL/Step',
            primerl__pb2.StepReq.SerializeToString,
            primerl__pb2.StepResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EndEpisode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/primerl.PrimeRL/EndEpisode',
            primerl__pb2.EndReq.SerializeToString,
            primerl__pb2.EndResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
