apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "primerl-servekit.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "primerl-servekit.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ (index .Values.models "llama3_8b").replicas | default 1 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "primerl-servekit.name" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "primerl-servekit.name" . }}
    spec:
      containers:
        - name: engine
          image: {{ (index .Values.models "llama3_8b").image }}
          env:
            - name: REDIS_URL
              value: redis://{{ include "primerl-servekit.redisHost" . }}:6379/0
          ports:
            - name: http
              containerPort: 9000
          resources:
            limits:
              nvidia.com/gpu: 1
        - name: bridge
          image: {{ .Values.bridgeImage | default "primerl/servekit:latest" }}
          env:
            - name: REDIS_URL
              value: redis://{{ include "primerl-servekit.redisHost" . }}:6379/0
          ports:
            - name: grpc
              containerPort: 50051
