apiVersion: v1
kind: Service
metadata:
  name: {{ include "primerl-servekit.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "primerl-servekit.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "primerl-servekit.name" . }}
  ports:
    - name: grpc
      port: 50051
      targetPort: grpc
    - name: http
      port: 9000
      targetPort: http
