# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: primerl.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'primerl.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rprimerl.proto\x12\x07primerl\"a\n\x08StartReq\x12\x0e\n\x06\x65nv_id\x18\x01 \x01(\t\x12\r\n\x05model\x18\x02 \x01(\t\x12\x11\n\tprompt_fp\x18\x03 \x01(\x0c\x12\x0e\n\x06prompt\x18\x04 \x01(\t\x12\x13\n\x0bpin_prefill\x18\x05 \x01(\x08\"2\n\tStartResp\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x11\n\tcache_hit\x18\x02 \x01(\x08\"k\n\x07StepReq\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x0b\n\x03obs\x18\x02 \x01(\t\x12\x16\n\x0emax_new_tokens\x18\x03 \x01(\x05\x12\x12\n\ngrammar_id\x18\x04 \x01(\t\x12\x13\n\x0bspeculative\x18\x05 \x01(\x08\"]\n\x08StepResp\x12\r\n\x05token\x18\x01 \x01(\t\x12\x0c\n\x04t_us\x18\x02 \x01(\x03\x12\x10\n\x08kv_bytes\x18\x03 \x01(\x03\x12\x10\n\x08\x62oundary\x18\x04 \x01(\x08\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x05 \x01(\x08\"\x1c\n\x06\x45ndReq\x12\x12\n\nsession_id\x18\x01 \x01(\t\"\x1a\n\x07\x45ndResp\x12\x0f\n\x07\x65victed\x18\x01 \x01(\x08\x32\xa2\x01\n\x07PrimeRL\x12\x35\n\x0cStartEpisode\x12\x11.primerl.StartReq\x1a\x12.primerl.StartResp\x12/\n\x04Step\x12\x10.primerl.StepReq\x1a\x11.primerl.StepResp(\x01\x30\x01\x12/\n\nEndEpisode\x12\x0f.primerl.EndReq\x1a\x10.primerl.EndRespb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'primerl_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STARTREQ']._serialized_start=26
  _globals['_STARTREQ']._serialized_end=123
  _globals['_STARTRESP']._serialized_start=125
  _globals['_STARTRESP']._serialized_end=175
  _globals['_STEPREQ']._serialized_start=177
  _globals['_STEPREQ']._serialized_end=284
  _globals['_STEPRESP']._serialized_start=286
  _globals['_STEPRESP']._serialized_end=379
  _globals['_ENDREQ']._serialized_start=381
  _globals['_ENDREQ']._serialized_end=409
  _globals['_ENDRESP']._serialized_start=411
  _globals['_ENDRESP']._serialized_end=437
  _globals['_PRIMERL']._serialized_start=440
  _globals['_PRIMERL']._serialized_end=602
# @@protoc_insertion_point(module_scope)
